### ISSUE TITLE
Compile (static) abseil for different C++ versions?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/abseil-cpp-feedstock#29]
Abseil has a bit of a special situation because the API changes with the C++ version (e.g. using `std::string_view` for C++17 and onwards, but `absl::string_view` below that). This can lead to pretty cryptic linker errors for projects consuming the C++ libs of abseil, because the wrong symbols will be present depending on the version that the target project is compiled with.

Considering that conda-forge allows individual projects to set different C++ standards, we should IMO consider using separate outputs depending on the cxx version used to compile (this minimum can be enforced with CMake's `target_compile_features` that's already [used](https://github.com/abseil/abseil-cpp/blob/20211102.0/CMake/AbseilHelpers.cmake#L257-L261) upstream but still off by default).

If I'm not off with this, the newest abseil-cpp builds are already effectively requiring C++17 (since https://github.com/conda-forge/abseil-cpp-feedstock/commit/fef86bfd67fca0ea0833a96b2678cf738f8fc3b3). I ran into this while testing older C++ standards in https://github.com/conda-forge/sentencepiece-feedstock/pull/26, and running into missing symbols on osx/linux where there weren't any when compiling with C++17.

CC @conda-forge/abseil-cpp

**Comment by xhochy** [comment]
The different outputs cannot co-exist in the same environment. Thus I would prefer to shift all projects to C++17 that need `abseil-cpp`. From what I have seen, there are projects that require a C++17 enabled Abseil whereas ones that don't require it still all support it.

**Comment by h-vetinari** [comment]
Just came up in discussion in #25 - apache/arrow is still at C++11, which means that if we want to have shared builds on windows (something I'd very much like to have), we'd be leaving them out in the cold, or forcing a huge C++ standard bump.

**Comment by h-vetinari** [comment]
Alternatively, we could separate the standards used to compile for windows (C++11) and unix (C++17)...

**Comment by h-vetinari** [comment]
I think at the very least, we should put the C++ version used to compile into the build_string...

**Comment by h-vetinari** [comment]
> It would not bump Arrow overall, just the conda-forge based builds.

From my understanding of the errors that @lidavidm reported in #25, arrow CI compiles against abseil (and grpc) from conda-forge.

**Comment by lidavidm** [comment]
Ah, I was unclear in #25, it's not all our CI builds that use conda-forge, just a subset. So yes, we could just move up the language standard for some of our builds (we still do need to support C++11 overall, but if the rest of conda-forge is moving to C++17 then that shouldn't be an issue for Arrow's conda-forge packages either I think)

**Comment by h-vetinari** [comment]
We could also compile static libs with other standards for those that cannot use our cxx_version (e.g. C++17). That way, downstream packages could still be compiled against a different cxx-baseline without colliding symbols etc.

**Comment by h-vetinari** [comment]
@conda-forge/core 

I believe that the decision to not impose a global C++ standard version (and letting feedstocks choose) is at odds with having abseil builds for only one C++ standard version (currently C++17 on unix, C++11 on windows). Since abseil's ABI changes based on the standard version used to compile, it leads to pretty obscure compilation and linker errors (though admittedly, the mismatch is not as sensitive on unix as it is on windows).

I'm aware of [CFEP 18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md), but I think this falls under the following caveat listed there:
> Building static archives (in separated packages) is still useful for some non-common workflows. These don't represent the majority of uses of our packages but can profit a lot from our using our existing infrastructure.

What would people think about building:
* one dynamic lib (say, C++17)
* one static lib each for C++11, C++14, C++17

That way, each feedstock could consume abseil in a compatible way _at least statically_; and if the consuming feedstock is C++17 compatible, they can also use the dynamic lib.

**Comment by h-vetinari** [comment]
Actually, windows cannot fully be built dynamically see [here](https://github.com/abseil/abseil-cpp/pull/1115#discussion_r838709189). I'm thinking it would be good to add
```
outputs:
  - name: libabseil_dynamic
    build:
      skip: True  # [win]
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ cxx_standard }}

  - name: libabseil_static
    build:
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ cxx_standard }}

  # choose sensible default per platform
  - name: libabseil
    requirements:
      host:
        - libabseil_dynamic ={{ version }}=*_cxx17  # [unix]
        - libabseil_static ={{ version }}=*_cxx11   # [win]

  # for compatibility
  - name: abseil-cpp
    requirements:
      host:
        - {{ pin_subpackage('libabseil', exact=True) }}
```

This is assuming we want to use this opportunity to resolve one more of the old `-cpp` remnants, cf. https://github.com/conda-forge/conda-forge.github.io/issues/1073.
